Nuitka version bump

diff --git a/.common/hooks/env b/.common/hooks/env
--- a/.common/hooks/env
+++ b/.common/hooks/env
@@ -9,7 +9,7 @@ QEMU_DIR='.qemu_static'
 IMPORTS_DIR='.imports'
 
 ARCH_YAML='arch.yaml'
-CONFIG_YAML="${DATA_DIR}/config.${DOCKER_TAG}${CONFIG_SUFFIX}.yaml"
+CONFIG_YAML="${CONFIG_YAML_OVERRIDE:-${DATA_DIR}/config.${DOCKER_TAG}${CONFIG_SUFFIX}.yaml}"
 
 #BUILD_PLATFORM_ARG='true'
 
@@ -23,6 +23,7 @@ CACHE_EXPIRY=604800
 DOCKER_FILE='Dockerfile'
 
 [ ! -d "${DATA_DIR}" ] && mkdir -p "${DATA_DIR}"
+[ ! -f "${CONFIG_YAML}" ] && touch "${CONFIG_YAML}"
 
 ## import config for this repo
 . "build.conf" || { echo 'No build.conf!'; exit 1; }
@@ -58,11 +59,15 @@ eval_param_ifn () {
 	param="${1}"
 	IFS=' ' read -a command <<< "${2}"
 
-	# >&2 echo "command: ${command[*]}"
-
-	[ -z "${!param}" ] \
-		&& value="$(eval "${command[*]}")" \
-		|| value="${!param}"
+	if [ -z "${!param}" ]; then
+		# [ ! -z "${DEBUG+set}" ] \
+		# 	&& >&2 echo "eval_param_ifn command: ${command[*]}"
+		value="$(eval "${command[*]}")"
+	else
+		# [ ! -z "${DEBUG+set}" ] \
+		# 	&& >&2 echo "eval_param_ifn: value exists"
+		value="${!param}"
+	fi
 
 	add_param "${value}" "${param}"
 }
@@ -73,6 +78,29 @@ eval_print_param_ifn () {
 
 	eval_param_ifn "${1}" "${3:-${2}}"
 	print_param "${!1}" "${desc:-${1}}"
+}
+
+function cleanup() { tput cnorm; }
+trap cleanup EXIT
+
+spinner() {
+	local pid=$!
+	local delay=0.5
+	local i=0
+
+	tput civis
+	while ps -a | awk '{print $1}' | grep -q "${pid}"; do
+	    c=`expr ${i} % 4`
+	    case ${c} in
+	       0) printf '/' ;;
+	       1) printf '-' ;;
+	       2) printf '\\' ;;
+	       3) printf '|' ;;
+	    esac
+	    i=`expr ${i} + 1`
+	    sleep $delay
+	    printf "\b"
+	done
 }
 
 ## curl the provided URL, handle errors and cache
@@ -86,16 +114,19 @@ get_url () {
 	if [ -f "${cache_file}" ] && [ "$(( $(date +"%s") - $(date -r "${cache_file}" +"%s") ))" -lt "${CACHE_EXPIRY}" ]; then
 		cat "${cache_file}"
 	else
-		page_data="$(curl -sL -w "%{http_code}\n" "${1}")"
+		>&2 printf 'Getting URL: %s.. ' "${1}"
+		page_data=$(curl -sL -w '%{http_code}\n' "${1}")
 		http_code="${page_data:(-3)}"
+
 		if [ "${http_code}" = "200" ]; then
 			echo "${page_data%???}" | tee "${cache_file}"
 		else
 			>&2 echo "URL: ${1}"
 			>&2 echo "cache file: $(echo "${1}" | md5sum | cut -d' ' -f1)"
-			>&2 echo "HTTP Error: ${http_code}"
+			>&2 printf 'HTTP Error: %s\n\n' "${http_code}"
 			return 1
 		fi
+		>&2 printf "\r$(tput el)"
 	fi
 }
 
@@ -105,15 +136,20 @@ git_api_data () {	get_url "https://api.github.com/repos/${1}/${2}"; }
 # git_api_element <repo> <request> <element>
 git_api_element () { git_api_data "${1}" "${2}" | sed -En 's|.*"'"${3}"'"\W+"([^"]+)".*|\1|p'; }
 
+# git_repo_releases <repo> (<element>)
+git_repo_releases () { git_api_element "${1}" 'releases' "${2:-tag_name}" | sort -uV; }
+
 # git_latest_release <repo> (<element>)
 git_latest_release () { git_api_element "${1}" 'releases/latest' "${2:-tag_name}"; }
+# git_latest_release <repo>
+# git_latest_release () {	git_repo_releases "${1}" | tail -n1; }
 
 # git_repo_tags <repo> (<element>)
-git_repo_tags () { git_api_element "${1}" 'tags' "${2:-name}" | sort -uV;
-}
+git_repo_tags () { git_api_element "${1}" 'tags' "${2:-name}" | sort -uV; }
 
 # git_latest_tag <repo> (<element>)
 # git_latest_tag () {	git_api_element "${1}" 'tags' "${2:-name}" | sort -uV | tail -n1; }
+# git_latest_tag <repo>
 git_latest_tag () {	git_repo_tags "${1}" | tail -n1; }
 
 # alpine_package_version <package> <alpine version> <repos>
@@ -169,7 +205,7 @@ parse_version_major () { echo "${1}" | awk -F \. '{print $1}'; }
 parse_version_minor () { echo "${1}" | awk -F \. '{print $1"."$2}'; }
 
 #
-# py_requireed_vesion() and python_get_module_from_string() needs a refactor,
+# py_required_vesion() and python_get_module_from_string() needs a refactor,
 # the whole python wheel thing was tacked on at the end, not really planned
 #
 
@@ -304,7 +340,7 @@ docker_api_get_repo () {
 	local repo && repo="${1}"
 	[[ "${repo}" != *"/"* ]] && repo="library/${repo}"
 
-	URL="https://registry.hub.docker.com/v2/repositories/${repo}/tags?page_size=100"
+	URL="https://registry.hub.docker.com/v2/repositories/${repo}/tags?page_size=1000"
 	while [ -n "${URL}" ]; do
 #		>&2 echo "Getting: ${URL}"
 		page="$(get_url "${URL}")"
@@ -443,15 +479,19 @@ get_manifest() {
 
 	manifest_file="${DATA_DIR}/manifest.${source_repo//\//_}.${source_image##*:}"
 
+	>&2 tput civis
+
 	if [ ! -f "${manifest_file}" ] || [ "$(( $(date +"%s") - $(date -r "${manifest_file}" +"%s") ))" -gt "${CACHE_EXPIRY}" ]; then
-		>&2 printf 'Fetching manifest: %s.. ' "${source_image}"
+		>&2 printf 'Fetching manifest: %s..           \b\b\b\b\b\b\b\b\b\b' "${source_image}"
 
 		manifest_cmd=("$(get_manifest_tool)" 'inspect' "${source_image}")
 		# pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")"
 		# >&2 printf '\n--- manifest command ---\n%s\n' "${pretty_manifest_cmd}"
 
+
 		local error
-		error="$("${manifest_cmd[@]}" 2>&1 1>"${manifest_file}")";
+		error="$("${manifest_cmd[@]}" 2>&1 1>"${manifest_file}")" &
+		>&2 spinner
 
 		# if there's an error try and determine the cause so we can decide whether to
 		# cache the failure by keeping the empty manifest file:
@@ -479,12 +519,14 @@ get_manifest() {
 			return 1
 		fi
 
-		>&2 echo
+		>&2 printf '\r'
 	# else
 	# 	>&2 printf 'Using cached manifest: %s\n' "${manifest_file}"
 	fi
+	>&2 tput cnorm
 	echo "${manifest_file}"
 }
+
 
 # ifFunc <func>
 ifFunc () { type "${1}" 2> /dev/null | sed "s/${1}//" | grep -qwi function; }
