reworked nuitka/build.conf

diff --git a/nuitka/Dockerfile b/nuitka/Dockerfile
--- a/nuitka/Dockerfile
+++ b/nuitka/Dockerfile
@@ -1,22 +1,22 @@
-ARG ALPINE_VERSION="3.13"
-ARG PYTHON_VERSION="3.8"
-ARG NUITKA_VERSION="0.6.12"
+#ARG ALPINE_VERSION="3.13"
+ARG BUILD_PYTHON_VERSION="3.9"
+ARG NUITKA_VERSION="0.6.16.4"
 
-#ARG FROM_IMAGE="python:${PYTHON_VERSION}-alpine"
-ARG FROM_IMAGE="alpine:${ALPINE_VERSION}"
+ARG FROM_IMAGE="python:${BUILD_PYTHON_VERSION}-alpine"
+#ARG FROM_IMAGE="alpine:${ALPINE_VERSION}"
 
 ## build the image
 #
 FROM "${FROM_IMAGE}"
 
 # QEMU static binaries from pre_build
-ARG QEMU_DIR
+ARG QEMU_DIR=""
 ARG QEMU_ARCH=""
 COPY _dummyfile "${QEMU_DIR}/qemu-${QEMU_ARCH}-static*" /usr/bin/
 
-ARG PYTHON_VERSION
+ARG BUILD_PYTHON_VERSION
 
-RUN apk -U add --no-cache \
+RUN apk add --no-cache \
 		cargo \
 		ccache \
 		chrpath \
@@ -25,19 +25,47 @@ RUN apk -U add --no-cache \
 		make \
 		musl-dev \
 		openssl-dev \
-		py3-pip \
-		py3-wheel \
-#		python3=~"${PYTHON_VERSION}" \
-#		python3-dev=~"${PYTHON_VERSION}" \
+#		py3-pip \
+#		py3-wheel \
+#		python3=~"${BUILD_PYTHON_VERSION}" \
+#		python3-dev=~"${BUILD_PYTHON_VERSION}" \
 		rust \
 		subversion
 
-ARG NUITKA_VERSION
+# version check in case we accidentally upgraded Python along the way
+RUN _pyver="$(python --version | sed -En 's|Python\s+([0-9.]*)|\1|p' | awk -F \. '{print $1"."$2}')" \
+	&& if [ "x${_pyver}" != "x${BUILD_PYTHON_VERSION}" ]; then \
+		echo "ERROR: Python reports version ${_pyver}, doesn't match build version ${BUILD_PYTHON_VERSION}"; \
+		echo "Exiting"; exit 1; fi
+
+ARG BUILDER_ROOT="/builder-root"
+WORKDIR "${BUILDER_ROOT}"
+
+ENV	VIRTUAL_ENV="${BUILDER_ROOT}/venv" \
+		PYTHONUNBUFFERED="1" \
+		PYTHONDONTWRITEBYTECODE="1" \
+		MAKEFLAGS="-j$(nproc)"
+
+RUN python -m pip install --upgrade virtualenv
+
+RUN python -m virtualenv --download "${VIRTUAL_ENV}"
+
+# Python wheels from pre_build
+ARG IMPORTS_DIR=".imports"
+ARG TARGET_ARCH_TAG=""
+COPY _dummyfile "${IMPORTS_DIR}/${TARGET_ARCH_TAG}*" "/${IMPORTS_DIR}/"
+
+# activate virtual env
+ENV PATH="${VIRTUAL_ENV}/bin:$PATH"
+
+ARG NUITKA_VERSION=""
 ENV LIBSODIUM_MAKE_ARGS="-j4"
 
-#	pip3 install --no-cache-dir --upgrade pip \
 RUN python3 -m pip install --no-cache-dir --upgrade pip \
-	&& pip3 install --no-cache-dir nuitka=="${NUITKA_VERSION}"
+	&& pip3 install --no-cache-dir --find-links "/${IMPORTS_DIR}/" nuitka=="${NUITKA_VERSION}"
+
+# cleanup, if we're squashing
+RUN rm -rf "/${IMPORTS_DIR}/"
 
 ENTRYPOINT ["python3","-m","nuitka"]
 
diff --git a/nuitka/Dockerfile.debian b/nuitka/Dockerfile.debian
--- a/nuitka/Dockerfile.debian
+++ b/nuitka/Dockerfile.debian
@@ -1,36 +1,56 @@
-ARG PYTHON_VERSION="3.8"
-ARG NUITKA_VERSION="0.6.12"
-ARG DEBIAN_RELEASE="buster"
+ARG BUILD_PYTHON_VERSION="3.9"
+ARG NUITKA_VERSION="0.6.16.4"
+ARG DEBIAN_RELEASE="bullseye"
 
-#ARG FROM_IMAGE="python:${PYTHON_VERSION}-${DEBIAN_RELEASE}"
-ARG FROM_IMAGE="debian:${DEBIAN_RELEASE}-slim"
+ARG FROM_IMAGE="python:${BUILD_PYTHON_VERSION}-${DEBIAN_RELEASE}"
+#ARG FROM_IMAGE="debian:${DEBIAN_RELEASE}-slim"
 
 ## build the image
 #
 FROM "${FROM_IMAGE}"
 
 # QEMU static binaries from pre_build
-ARG QEMU_DIR
+ARG QEMU_DIR=""
 ARG QEMU_ARCH=""
 COPY _dummyfile "${QEMU_DIR}/qemu-${QEMU_ARCH}-static*" /usr/bin/
 
 RUN apt-get update \
-	&& apt-get install -qy \
+	&& apt-get install -qy --no-install-recommends \
 		cargo \
 		ccache \
 		chrpath \
-		python3-dev \
-		python3-pip \
-		python3-wheel \
+#		python3-dev \
+#		python3-pip \
+#		python3-wheel \
 		rustc \
 		subversion
 
-ARG NUITKA_VERSION
+# version check in case we accidentally upgraded Python along the way
+RUN _pyver="$(python --version | sed -En 's|Python\s+([0-9.]*)|\1|p' | awk -F \. '{print $1"."$2}')" \
+	&& if [ "x${_pyver}" != "x${BUILD_PYTHON_VERSION}" ]; then \
+		echo "ERROR: Python reports version ${_pyver}, doesn't match build version ${BUILD_PYTHON_VERSION}"; \
+		echo "Exiting"; exit 1; fi
+
+ARG BUILDER_ROOT="/builder-root"
+WORKDIR "${BUILDER_ROOT}"
+
+ENV	VIRTUAL_ENV="${BUILDER_ROOT}/venv" \
+		PYTHONUNBUFFERED="1" \
+		PYTHONDONTWRITEBYTECODE="1" \
+		MAKEFLAGS="-j$(nproc)"
+
+RUN python -m pip install --upgrade virtualenv
+
+RUN python -m virtualenv --download "${VIRTUAL_ENV}"
+
+# activate virtual env
+ENV PATH="${VIRTUAL_ENV}/bin:$PATH"
+
+ARG NUITKA_VERSION=""
 ENV LIBSODIUM_MAKE_ARGS="-j4"
 
 RUN python3 -m pip install --no-cache-dir --upgrade pip \
-	&& python3 -m pip install --no-cache-dir nuitka=="${NUITKA_VERSION}"
-
+	&& pip3 install --no-cache-dir nuitka=="${NUITKA_VERSION}"
 
 ENTRYPOINT ["python3","-m","nuitka"]
 
